### ISSUE TITLE
Add namespaceSelector and/or matchLabels

### ISSUE THREAD

**Issue by gd-jroberts** [reactiveops/rbac-manager#34]
Similar to how network policies are implemented, it would be extremely helpful for our use-case if rbac-manager could dynamically create role-bindings in namespaces selected via name and/or a label selector.

We have N number of dynamically provisioned namespaces and we'd like to have rbac definitions applied to all based upon selection criteria, but also have newly added namespaces matching the same criteria be automatically updated.

**Comment by robscott** [comment]
Hey @gd-jroberts, that's a really great idea! I'm thinking allowing `namespaceSelector` attributes to be used as an alternative to `namespace` attributes would be really powerful.

Here's a theoretical example of both working in the same role binding:
```
rbacBindings:
  - name: joe
    subjects:
      - kind: User
        name: joe@example.com
    roleBindings:
      - namespaceSelector: 
           matchLabels:
             example: label
        clusterRole: view
      - namespace: web
        clusterRole: edit
```

Is that the kind of approach you were thinking of?
